#!/usr/bin/python

import logging
import aeolus.common
import aeolus.maker

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger()

# 1. Get aeolus files

# 2. Call Zephyrus on them

# 3. Unmerge solution files

# 4. Call METIS

import argparse

parser = argparse.ArgumentParser(prog='armonic-aeolus-unmerge')
parser.add_argument('-ic', '--input-configuration', type=str, required=True)
parser.add_argument('-spec', '--specification', type=str, required=True)
parser.add_argument('-w', '--workspace', type=str, required=True)

#parser.add_argument('-a', '--armonic-info', type=str, required=True)
#parser.add_argument('-o', '--output-directory', type=str, required=True)

args = parser.parse_args()

aeolus.maker.run(args.workspace + "/", args.input_configuration, args.specification)

